### PR TITLE
Fix for one of your issues

### PR DESCRIPTION
**Pull request by christocracy**
https://github.com/collectiveidea/delayed_job/issues/92

Fix DM.  Model.find returns an Iterator -- not an instance.  Must use Model.get instead

def self.yaml_new(klass, tag, val)

```
klass.get(val['id'])  #<-- YES!  DM returns an instance

#klass.find(val['id']) #<-- NO!  DM returns an Iterator.
```

  end

### CODE REVIEW

**Comment by myobie** [comment]
It's been in since way back in 0.9. DataMapper uses get. DM's find is not like ActiveRecord's find. I can add a spec later, but honestly #find should have never been used in the first place.

**Comment by myobie** [comment]
Actually, it looks like it's been fixed in master, but a gem hasn't been released. What is the release schedule for a new version? Currently, I am monkey patching to fix it.

**Comment by bryckbost** [comment]
@myoble: Soon. We're working on getting each of the backends up to date and make sure they're working with the proper yaml parsing libraries. Closing this as it has been fixed in 9751a93e3cdead6ddc6fb5f7d1c6b9bfcde16697.

**Comment by neilchaudhuri** [comment]
Using the latest versions of DM, DJ, and DJDM, I am finding precisely the same bug--calling AR's find to retrieve a single record by id rather than DM's get. Has this truly been fixed? If not, any advice on where to add the monkey patch is appreciated.

Thanks.

**Comment by neilchaudhuri** [comment]
Right after I sent the last message I found this in data_mapper.rb:

def self.find id
     get id
end

That seems correct, but any advice on why this isn't taking effect is appreciated.

**Comment by christocracy** [comment]
I remember going down this road and figuring it out, can't remember now.  I think I ended up forking an hacking a fix, will dig.

Snet form my iPhone

**Comment by neilchaudhuri** [comment]
That would be great. Just for kicks, I tried to workaround this by changing my performable method to take an id so I could do the get (and not find) myself. However, now I am getting NameError: uninitialized constant. In my Gemfile I have 

gem "delayed_job_data_mapper"

so I don't know what the problem is.

Thanks.

**Comment by christocracy** [comment]
See my github profile, I'm sure I forked this and hacked a fix.  Sorry, in bed still ;)

Snet form my iPhone

**Comment by christocracy** [comment]
https://github.com/christocracy/delayed_job_data_mapper

Snet form my iPhone

**Comment by neilchaudhuri** [comment]
Thanks. That worked for me.

**Comment by christocracy** [comment]
Right on!

Snet form my iPhone

**Pull request closed without merging**
